# basic options
title: Maxicozy Datascience Portfolio
email: max_vander_werf@hotmail.com
#description: Datascience Portfolio 
twitter_username:  MaxFM96
github_username:  MaxvanderWerf

# Build settings
markdown: kramdown
theme: minima

# Header
header_pages:
  - about.md
  - projects.md
  - recommendations.md
