# basic options
title: Max van der Werf - Datascience Portfolio
email: max_vander_werf@hotmail.com
#description: Datascience Portfolio 
twitter_username:  WerfMax
github_username:  MaxvanderWerf

# Build settings
markdown: kramdown
theme: minima

# Header
header_pages:
  - projects.md
  - coursework.md
  - recommendations.md
