# basic options
title: Your awesome title
author: GitHub User
email: max_vander_werf@hotmail.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  MaxvanderWerf

# Build settings
markdown: kramdown
theme: minima
