# basic options
title: Maxicozy Datscience Portfolio
author: MaxvanderWerf
email: max_vander_werf@hotmail.com
description: My Datascience Portfolio
twitter_username:  MaxFM96
github_username:  MaxvanderWerf

# Build settings
markdown: kramdown
theme: minima
